{application,vsh,
             [{config_mtime,1769643312},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,crypto,jason]},
              {description,"Valence Shell - Formally Verified Reversible Shell"},
              {modules,['Elixir.Mix.Tasks.Vsh.Daemon','Elixir.VSH',
                        'Elixir.VSH.Application','Elixir.VSH.Daemon',
                        'Elixir.VSH.Filesystem','Elixir.VSH.Filesystem.State',
                        'Elixir.VSH.NIF','Elixir.VSH.NIF.Manifest',
                        'Elixir.VSH.State']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.VSH.Application',[]}}]}.
